# Generated by Django 5.1 on 2025-01-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emplyees', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=30)),
            ],
        ),
    ]
