# Generated by Django 5.1 on 2025-02-05 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dhyey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employers',
            new_name='Student',
        ),
    ]
