# Generated by Django 5.1 on 2025-02-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dhyey', '0002_rename_employers_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
