# Generated by Django 5.1 on 2025-02-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dhyey', '0003_student_email_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='emplyees',
            new_name='name',
        ),
    ]
