# Generated by Django 5.1 on 2025-02-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dhyey', '0004_rename_emplyees_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subjects', models.CharField(max_length=20)),
            ],
        ),
    ]
