# Generated by Django 5.1.7 on 2025-03-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(default='zxy099@gmail.com', max_length=254)),
            ],
        ),
    ]
